name: Build OpenWrt
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Installation depends
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede
    - name: Add source ssrp & passwall
      run: |
        cd lede
        echo 'src-git helloworld https://github.com/fw876/helloworld' >>feeds.conf.default
        echo 'src-git passwall https://github.com/xiaorouji/openwrt-passwall' >>feeds.conf.default
    - name: Clone openclash
      run: |
        wget https://github.com/vernesong/OpenClash/archive/master.zip
        unzip master.zip
        mv OpenClash-master/luci-app-openclash lede/package
    - name: Update and install feeds
      run: |
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Generate config file
      run: |
        cd lede
        rm -f ./.config*
        touch ./.config
        cat >> .config <<EOF
        #
        # ========================固件定制部分========================
        #
        # 
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_DEVICE_generic=y
        # CONFIG_GRUB_EFI_IMAGES is not set
        CONFIG_GRUB_IMAGES=y
        CONFIG_PACKAGE_6in4=y
        CONFIG_PACKAGE_TURBOACC_INCLUDE_DNSFORWARDER=y
        CONFIG_PACKAGE_TURBOACC_INCLUDE_DNSPROXY=y
        # CONFIG_PACKAGE_automount is not set
        # CONFIG_PACKAGE_autosamba is not set
        CONFIG_PACKAGE_bash=y
        CONFIG_PACKAGE_boost=y
        CONFIG_PACKAGE_boost-date_time=y
        CONFIG_PACKAGE_boost-program_options=y
        CONFIG_PACKAGE_boost-system=y
        CONFIG_PACKAGE_ca-certificates=y
        CONFIG_PACKAGE_coreutils-nohup=y
        CONFIG_PACKAGE_dnsforwarder=y
        CONFIG_PACKAGE_dnsproxy=y
        CONFIG_PACKAGE_glib2=y
        CONFIG_PACKAGE_haproxy=y
        CONFIG_PACKAGE_ip6tables=y
        CONFIG_PACKAGE_ipt2socks=y
        CONFIG_PACKAGE_iptables-mod-extra=y
        CONFIG_PACKAGE_ipv6helper=y
        CONFIG_PACKAGE_kmod-fuse=y
        CONFIG_PACKAGE_kmod-ipt-extra=y
        CONFIG_PACKAGE_kmod-ipt-nat6=y
        CONFIG_PACKAGE_kmod-iptunnel=y
        CONFIG_PACKAGE_kmod-nf-nat6=y
        CONFIG_PACKAGE_kmod-sit=y
        CONFIG_PACKAGE_libatomic=y
        CONFIG_PACKAGE_libattr=y
        CONFIG_PACKAGE_libcap=y
        CONFIG_PACKAGE_libcap-bin=y
        CONFIG_PACKAGE_libcap-bin-capsh-shell="/bin/sh"
        CONFIG_PACKAGE_libdb47=y
        CONFIG_PACKAGE_libffi=y
        CONFIG_PACKAGE_libfuse=y
        CONFIG_PACKAGE_libltdl=y
        CONFIG_PACKAGE_liblua5.3=y
        CONFIG_PACKAGE_libruby=y
        CONFIG_PACKAGE_libtirpc=y
        CONFIG_PACKAGE_libyaml=y
        # CONFIG_PACKAGE_luci-app-accesscontrol is not set
        # CONFIG_PACKAGE_luci-app-adbyby-plus is not set
        # CONFIG_PACKAGE_luci-app-autoreboot is not set
        # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
        CONFIG_PACKAGE_luci-app-openclash=y
        CONFIG_PACKAGE_luci-app-passwall=y
        # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Server is not set
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_GO=y
        # CONFIG_PACKAGE_luci-app-qbittorrent is not set
        # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Server is not set
        # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Libev_Server is not set
        CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
        # CONFIG_PACKAGE_luci-app-unblockmusic is not set
        # CONFIG_PACKAGE_luci-app-upnp is not set
        # CONFIG_PACKAGE_luci-app-uugamebooster is not set
        # CONFIG_PACKAGE_luci-app-vlmcsd is not set
        # CONFIG_PACKAGE_luci-app-vsftpd is not set
        # CONFIG_PACKAGE_luci-app-wol is not set
        CONFIG_PACKAGE_luci-app-wrtbwmon=y
        # CONFIG_PACKAGE_luci-app-xlnetacc is not set
        CONFIG_PACKAGE_luci-i18n-passwall-zh-cn=y
        CONFIG_PACKAGE_luci-i18n-wrtbwmon-zh-cn=y
        CONFIG_PACKAGE_luci-proto-ipv6=y
        CONFIG_PACKAGE_luci-theme-argon=y
        CONFIG_PACKAGE_luci-theme-material=y
        CONFIG_PACKAGE_luci-theme-netgear=y
        CONFIG_PACKAGE_odhcp6c=y
        CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
        CONFIG_PACKAGE_odhcpd-ipv6only=y
        CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
        CONFIG_PACKAGE_open-vm-tools=y
        CONFIG_PACKAGE_open-vm-tools-fuse=y
        CONFIG_PACKAGE_ruby=y
        CONFIG_PACKAGE_ruby-bigdecimal=y
        CONFIG_PACKAGE_ruby-date=y
        CONFIG_PACKAGE_ruby-dbm=y
        CONFIG_PACKAGE_ruby-digest=y
        CONFIG_PACKAGE_ruby-enc=y
        CONFIG_PACKAGE_ruby-forwardable=y
        CONFIG_PACKAGE_ruby-pstore=y
        CONFIG_PACKAGE_ruby-psych=y
        CONFIG_PACKAGE_ruby-stringio=y
        CONFIG_PACKAGE_ruby-strscan=y
        CONFIG_PACKAGE_ruby-yaml=y
        CONFIG_PACKAGE_trojan=y
        CONFIG_PACKAGE_trojan-go=y
        CONFIG_PACKAGE_trojan-plus=y
        CONFIG_PACKAGE_unzip=y
        CONFIG_PACKAGE_v2ray-plugin=y
        CONFIG_PACKAGE_xray-geodata=y
        CONFIG_TARGET_IMAGES_GZIP=y
        CONFIG_TARGET_ROOTFS_PARTSIZE=240
        CONFIG_TROJAN_GO_COMPRESS_UPX=y
        CONFIG_boost-compile-visibility-hidden=y
        CONFIG_boost-runtime-shared=y
        CONFIG_boost-static-and-shared-libs=y
        CONFIG_boost-variant-release=y
        CONFIG_PACKAGE_SAMBA_MAX_DEBUG_LEVEL=-1
        CONFIG_PACKAGE_UnblockNeteaseMusic-Go=y
        CONFIG_PACKAGE_adbyby=y
        CONFIG_PACKAGE_antfs-mount=y
        CONFIG_PACKAGE_etherwake=y
        CONFIG_PACKAGE_grub2-efi=y
        CONFIG_PACKAGE_iptables-mod-ipsec=y
        CONFIG_PACKAGE_kmod-crypto-acompress=y
        CONFIG_PACKAGE_kmod-crypto-cbc=y
        CONFIG_PACKAGE_kmod-crypto-deflate=y
        CONFIG_PACKAGE_kmod-crypto-des=y
        CONFIG_PACKAGE_kmod-crypto-echainiv=y
        CONFIG_PACKAGE_kmod-crypto-md5=y
        CONFIG_PACKAGE_kmod-fs-antfs=y
        CONFIG_PACKAGE_kmod-fs-exfat=y
        CONFIG_PACKAGE_kmod-fs-ext4=y
        # CONFIG_PACKAGE_kmod-ip-vti is not set
        # CONFIG_PACKAGE_kmod-ip6-vti is not set
        CONFIG_PACKAGE_kmod-ipsec=y
        CONFIG_PACKAGE_kmod-ipsec4=y
        CONFIG_PACKAGE_kmod-ipsec6=y
        CONFIG_PACKAGE_kmod-ipt-ipsec=y
        CONFIG_PACKAGE_kmod-iptunnel6=y
        CONFIG_PACKAGE_kmod-lib-crc16=y
        CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
        CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
        CONFIG_PACKAGE_kmod-scsi-core=y
        CONFIG_PACKAGE_kmod-usb-storage=y
        CONFIG_PACKAGE_kmod-usb-storage-extras=y
        CONFIG_PACKAGE_kmod-usb-storage-uas=y
        # CONFIG_PACKAGE_kmod-xfrm-interface is not set
        CONFIG_PACKAGE_libcares=y
        CONFIG_PACKAGE_luci-app-samba=y
        # CONFIG_PACKAGE_luci-i18n-samba-ca is not set
        # CONFIG_PACKAGE_luci-i18n-samba-cs is not set
        # CONFIG_PACKAGE_luci-i18n-samba-de is not set
        # CONFIG_PACKAGE_luci-i18n-samba-el is not set
        # CONFIG_PACKAGE_luci-i18n-samba-en is not set
        # CONFIG_PACKAGE_luci-i18n-samba-es is not set
        # CONFIG_PACKAGE_luci-i18n-samba-fr is not set
        # CONFIG_PACKAGE_luci-i18n-samba-he is not set
        # CONFIG_PACKAGE_luci-i18n-samba-hu is not set
        # CONFIG_PACKAGE_luci-i18n-samba-it is not set
        # CONFIG_PACKAGE_luci-i18n-samba-ja is not set
        # CONFIG_PACKAGE_luci-i18n-samba-ms is not set
        # CONFIG_PACKAGE_luci-i18n-samba-no is not set
        # CONFIG_PACKAGE_luci-i18n-samba-pl is not set
        # CONFIG_PACKAGE_luci-i18n-samba-pt is not set
        # CONFIG_PACKAGE_luci-i18n-samba-pt-br is not set
        # CONFIG_PACKAGE_luci-i18n-samba-ro is not set
        # CONFIG_PACKAGE_luci-i18n-samba-ru is not set
        # CONFIG_PACKAGE_luci-i18n-samba-sk is not set
        # CONFIG_PACKAGE_luci-i18n-samba-sv is not set
        # CONFIG_PACKAGE_luci-i18n-samba-tr is not set
        # CONFIG_PACKAGE_luci-i18n-samba-uk is not set
        # CONFIG_PACKAGE_luci-i18n-samba-vi is not set
        CONFIG_PACKAGE_luci-i18n-samba-zh-cn=y
        # CONFIG_PACKAGE_luci-i18n-samba-zh-tw is not set
        CONFIG_PACKAGE_miniupnpd=y
        CONFIG_PACKAGE_qBittorrent-static=y
        CONFIG_PACKAGE_samba36-server=y
        CONFIG_PACKAGE_shadowsocks-libev-ss-server=y
        CONFIG_PACKAGE_shadowsocksr-libev-ssr-server=y
        CONFIG_PACKAGE_strongswan=y
        CONFIG_PACKAGE_strongswan-charon=y
        # CONFIG_PACKAGE_strongswan-charon-cmd is not set
        # CONFIG_PACKAGE_strongswan-default is not set
        # CONFIG_PACKAGE_strongswan-gencerts is not set
        CONFIG_PACKAGE_strongswan-ipsec=y
        # CONFIG_PACKAGE_strongswan-isakmp is not set
        # CONFIG_PACKAGE_strongswan-libnttfft is not set
        # CONFIG_PACKAGE_strongswan-libtls is not set
        CONFIG_PACKAGE_strongswan-minimal=y
        # CONFIG_PACKAGE_strongswan-mod-addrblock is not set
        CONFIG_PACKAGE_strongswan-mod-aes=y
        # CONFIG_PACKAGE_strongswan-mod-af-alg is not set
        # CONFIG_PACKAGE_strongswan-mod-agent is not set
        # CONFIG_PACKAGE_strongswan-mod-attr is not set
        # CONFIG_PACKAGE_strongswan-mod-attr-sql is not set
        # CONFIG_PACKAGE_strongswan-mod-bliss is not set
        # CONFIG_PACKAGE_strongswan-mod-blowfish is not set
        # CONFIG_PACKAGE_strongswan-mod-ccm is not set
        # CONFIG_PACKAGE_strongswan-mod-chapoly is not set
        # CONFIG_PACKAGE_strongswan-mod-cmac is not set
        # CONFIG_PACKAGE_strongswan-mod-connmark is not set
        # CONFIG_PACKAGE_strongswan-mod-constraints is not set
        # CONFIG_PACKAGE_strongswan-mod-coupling is not set
        # CONFIG_PACKAGE_strongswan-mod-ctr is not set
        # CONFIG_PACKAGE_strongswan-mod-curl is not set
        # CONFIG_PACKAGE_strongswan-mod-curve25519 is not set
        # CONFIG_PACKAGE_strongswan-mod-des is not set
        # CONFIG_PACKAGE_strongswan-mod-dhcp is not set
        # CONFIG_PACKAGE_strongswan-mod-dnskey is not set
        # CONFIG_PACKAGE_strongswan-mod-duplicheck is not set
        # CONFIG_PACKAGE_strongswan-mod-eap-identity is not set
        # CONFIG_PACKAGE_strongswan-mod-eap-md5 is not set
        # CONFIG_PACKAGE_strongswan-mod-eap-mschapv2 is not set
        # CONFIG_PACKAGE_strongswan-mod-eap-radius is not set
        # CONFIG_PACKAGE_strongswan-mod-eap-tls is not set
        # CONFIG_PACKAGE_strongswan-mod-farp is not set
        # CONFIG_PACKAGE_strongswan-mod-fips-prf is not set
        # CONFIG_PACKAGE_strongswan-mod-forecast is not set
        # CONFIG_PACKAGE_strongswan-mod-gcm is not set
        # CONFIG_PACKAGE_strongswan-mod-gcrypt is not set
        CONFIG_PACKAGE_strongswan-mod-gmp=y
        # CONFIG_PACKAGE_strongswan-mod-gmpdh is not set
        # CONFIG_PACKAGE_strongswan-mod-ha is not set
        CONFIG_PACKAGE_strongswan-mod-hmac=y
        CONFIG_PACKAGE_strongswan-mod-kernel-libipsec=y
        CONFIG_PACKAGE_strongswan-mod-kernel-netlink=y
        # CONFIG_PACKAGE_strongswan-mod-ldap is not set
        # CONFIG_PACKAGE_strongswan-mod-led is not set
        # CONFIG_PACKAGE_strongswan-mod-load-tester is not set
        # CONFIG_PACKAGE_strongswan-mod-md4 is not set
        # CONFIG_PACKAGE_strongswan-mod-md5 is not set
        # CONFIG_PACKAGE_strongswan-mod-mgf1 is not set
        # CONFIG_PACKAGE_strongswan-mod-mysql is not set
        # CONFIG_PACKAGE_strongswan-mod-newhope is not set
        CONFIG_PACKAGE_strongswan-mod-nonce=y
        # CONFIG_PACKAGE_strongswan-mod-ntru is not set
        # CONFIG_PACKAGE_strongswan-mod-openssl is not set
        # CONFIG_PACKAGE_strongswan-mod-pem is not set
        # CONFIG_PACKAGE_strongswan-mod-pgp is not set
        # CONFIG_PACKAGE_strongswan-mod-pkcs1 is not set
        # CONFIG_PACKAGE_strongswan-mod-pkcs11 is not set
        # CONFIG_PACKAGE_strongswan-mod-pkcs12 is not set
        # CONFIG_PACKAGE_strongswan-mod-pkcs7 is not set
        # CONFIG_PACKAGE_strongswan-mod-pkcs8 is not set
        CONFIG_PACKAGE_strongswan-mod-pubkey=y
        CONFIG_PACKAGE_strongswan-mod-random=y
        # CONFIG_PACKAGE_strongswan-mod-rc2 is not set
        # CONFIG_PACKAGE_strongswan-mod-resolve is not set
        # CONFIG_PACKAGE_strongswan-mod-revocation is not set
        CONFIG_PACKAGE_strongswan-mod-sha1=y
        # CONFIG_PACKAGE_strongswan-mod-sha2 is not set
        # CONFIG_PACKAGE_strongswan-mod-sha3 is not set
        # CONFIG_PACKAGE_strongswan-mod-smp is not set
        CONFIG_PACKAGE_strongswan-mod-socket-default=y
        # CONFIG_PACKAGE_strongswan-mod-socket-dynamic is not set
        # CONFIG_PACKAGE_strongswan-mod-sql is not set
        # CONFIG_PACKAGE_strongswan-mod-sqlite is not set
        # CONFIG_PACKAGE_strongswan-mod-sshkey is not set
        CONFIG_PACKAGE_strongswan-mod-stroke=y
        # CONFIG_PACKAGE_strongswan-mod-test-vectors is not set
        # CONFIG_PACKAGE_strongswan-mod-uci is not set
        # CONFIG_PACKAGE_strongswan-mod-unity is not set
        CONFIG_PACKAGE_strongswan-mod-updown=y
        # CONFIG_PACKAGE_strongswan-mod-vici is not set
        # CONFIG_PACKAGE_strongswan-mod-whitelist is not set
        CONFIG_PACKAGE_strongswan-mod-x509=y
        # CONFIG_PACKAGE_strongswan-mod-xauth-eap is not set
        CONFIG_PACKAGE_strongswan-mod-xauth-generic=y
        CONFIG_PACKAGE_strongswan-mod-xcbc=y
        # CONFIG_PACKAGE_strongswan-pki is not set
        # CONFIG_PACKAGE_strongswan-scepclient is not set
        # CONFIG_PACKAGE_strongswan-swanctl is not set
        CONFIG_PACKAGE_uugamebooster=y
        CONFIG_PACKAGE_vlmcsd=y
        CONFIG_PACKAGE_vsftpd-alt=y
        CONFIG_PACKAGE_wol=y
        CONFIG_PACKAGE_wsdd2=y
        # CONFIG_PACKAGE_xfrm is not set
        CONFIG_STRONGSWAN_ROUTING_TABLE="220"
        CONFIG_STRONGSWAN_ROUTING_TABLE_PRIO="220"
        CONFIG_VSFTPD_USE_UCI_SCRIPTS=y
        #
        # ========================固件定制部分结束========================
        #
        EOF
        sed -i 's/^[ \t]*//g' ./.config
        make defconfig
        # 网络配置信息，将从 zzz-default-settings 文件的第2行开始添加
        sed -i "2i # network config" ./package/lean/default-settings/files/zzz-default-settings
        # 默认 IP 地址，旁路由时不会和主路由的 192.168.1.1 冲突
        sed -i "3i uci set network.lan.ipaddr='192.168.50.6'" ./package/lean/default-settings/files/zzz-default-settings
        sed -i "4i uci set network.lan.proto='static'" ./package/lean/default-settings/files/zzz-default-settings # 静态 IP
        sed -i "5i uci set network.lan.type='bridge'" ./package/lean/default-settings/files/zzz-default-settings  # 接口类型：桥接
        sed -i "6i uci set network.lan.ifname='eth0'" ./package/lean/default-settings/files/zzz-default-settings  # 网络端口：默认 eth0，第一个接口
        sed -i "7i uci set network.lan.netmask='255.255.255.0'" ./package/lean/default-settings/files/zzz-default-settings    # 子网掩码
        sed -i "8i uci set network.lan.gateway='192.168.50.1'" ./package/lean/default-settings/files/zzz-default-settings  # 默认网关地址（主路由 IP）
        sed -i "9i uci set network.lan.dns='192.168.50.1'" ./package/lean/default-settings/files/zzz-default-settings  # 默认上游 DNS 地址
        sed -i "10i uci commit network\n" ./package/lean/default-settings/files/zzz-default-settings
    - name: Download package
      run: |
        cd lede && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build
      run: |
        cd lede
        make -j$(nproc)
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: lede/bin
