name: Build OpenWrt0724
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true        
    - name: Checkout
      uses: actions/checkout@v3.1.0        
    - name: Disk space
      run: |
           echo "Free space:"
           df -h
            
    - name: Installation depends
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev python3-setuptools
    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede
    - name: Add source ssrp & passwall
      run: |
        cd lede
        echo 'src-git helloworld https://github.com/fw876/helloworld' >>feeds.conf.default
       # echo 'src-git passwall https://github.com/xiaorouji/openwrt-passwall' >>feeds.conf.default
    - name: Clone openclash
      run: |
        wget https://github.com/vernesong/OpenClash/archive/master.zip
        unzip master.zip
        mv OpenClash-master/luci-app-openclash lede/package
    - name: Update and install feeds
      run: |
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Generate config file
      run: |
        cd lede
        rm -f ./.config*
        touch ./.config
        cat >> .config <<EOF
        #
        # ========================固件定制部分========================
        #
        # 
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_DEVICE_generic=y
        CONFIG_PACKAGE_6in4=y
        # CONFIG_PACKAGE_UnblockNeteaseMusic-Go is not set
        # CONFIG_PACKAGE_adbyby is not set
        CONFIG_PACKAGE_bash=y
        CONFIG_PACKAGE_boost=y
        CONFIG_PACKAGE_boost-date_time=y
        CONFIG_PACKAGE_boost-program_options=y
        CONFIG_PACKAGE_boost-system=y
        CONFIG_PACKAGE_ca-certificates=y
        CONFIG_PACKAGE_coreutils-nohup=y
        # CONFIG_PACKAGE_etherwake is not set
        CONFIG_PACKAGE_glib2=y
        CONFIG_PACKAGE_ip6tables=y
        CONFIG_PACKAGE_ipt2socks=y
        CONFIG_PACKAGE_iptables-mod-extra=y
        # CONFIG_PACKAGE_iptables-mod-ipsec is not set
        CONFIG_PACKAGE_ipv6helper=y
        # CONFIG_PACKAGE_kmod-crypto-cbc is not set
        # CONFIG_PACKAGE_kmod-crypto-deflate is not set
        # CONFIG_PACKAGE_kmod-crypto-des is not set
        # CONFIG_PACKAGE_kmod-crypto-echainiv is not set
        # CONFIG_PACKAGE_kmod-crypto-hmac is not set
        # CONFIG_PACKAGE_kmod-crypto-kpp is not set
        # CONFIG_PACKAGE_kmod-crypto-md5 is not set
        CONFIG_PACKAGE_kmod-fuse=y
        CONFIG_PACKAGE_kmod-inet-diag=y
        # CONFIG_PACKAGE_kmod-ipsec is not set
        CONFIG_PACKAGE_kmod-ipt-extra=y
        # CONFIG_PACKAGE_kmod-ipt-ipsec is not set
        CONFIG_PACKAGE_kmod-ipt-nat6=y
        CONFIG_PACKAGE_kmod-iptunnel=y
        # CONFIG_PACKAGE_kmod-iptunnel6 is not set
        CONFIG_PACKAGE_kmod-nf-nat6=y
        CONFIG_PACKAGE_kmod-sit=y
        # CONFIG_PACKAGE_kmod-wireguard is not set
        CONFIG_PACKAGE_libattr=y
        CONFIG_PACKAGE_libcap-bin=y
        CONFIG_PACKAGE_libcap-bin-capsh-shell="/bin/sh"
        # CONFIG_PACKAGE_libcares is not set
        CONFIG_PACKAGE_libdb47=y
        CONFIG_PACKAGE_libffi=y
        CONFIG_PACKAGE_libfuse=y
        # CONFIG_PACKAGE_libminiupnpc is not set
        # CONFIG_PACKAGE_libnatpmp is not set
        CONFIG_PACKAGE_libruby=y
        CONFIG_PACKAGE_libtirpc=y
        CONFIG_PACKAGE_libyaml=y
        # CONFIG_PACKAGE_luci-app-adbyby-plus is not set
        # CONFIG_PACKAGE_luci-app-ddns is not set
        # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
        CONFIG_PACKAGE_luci-app-openclash=y
        CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_IPT2Socks=y
        # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Server is not set
        # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Libev_Server is not set
        CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
        # CONFIG_PACKAGE_luci-app-unblockmusic is not set
        # CONFIG_PACKAGE_luci-app-unblockmusic_INCLUDE_UnblockNeteaseMusic_Go is not set
        # CONFIG_PACKAGE_luci-app-vlmcsd is not set
        # CONFIG_PACKAGE_luci-app-wireguard is not set
        # CONFIG_PACKAGE_luci-app-wol is not set
        # CONFIG_PACKAGE_luci-app-xlnetacc is not set
        # CONFIG_PACKAGE_luci-app-zerotier is not set
        CONFIG_PACKAGE_luci-proto-ipv6=y
        # CONFIG_PACKAGE_luci-proto-wireguard is not set
        CONFIG_PACKAGE_luci-theme-argon=y
        CONFIG_PACKAGE_luci-theme-material=y
        CONFIG_PACKAGE_luci-theme-netgear=y
        CONFIG_PACKAGE_odhcp6c=y
        CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
        CONFIG_PACKAGE_odhcpd-ipv6only=y
        CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
        CONFIG_PACKAGE_open-vm-tools=y
        CONFIG_PACKAGE_open-vm-tools-fuse=y
        CONFIG_PACKAGE_ruby=y
        CONFIG_PACKAGE_ruby-bigdecimal=y
        CONFIG_PACKAGE_ruby-date=y
        CONFIG_PACKAGE_ruby-dbm=y
        CONFIG_PACKAGE_ruby-digest=y
        CONFIG_PACKAGE_ruby-enc=y
        CONFIG_PACKAGE_ruby-forwardable=y
        CONFIG_PACKAGE_ruby-pstore=y
        CONFIG_PACKAGE_ruby-psych=y
        CONFIG_PACKAGE_ruby-stringio=y
        CONFIG_PACKAGE_ruby-strscan=y
        CONFIG_PACKAGE_ruby-yaml=y
        # CONFIG_PACKAGE_shadowsocks-libev-ss-server is not set
        # CONFIG_PACKAGE_shadowsocksr-libev-ssr-server is not set
        # CONFIG_PACKAGE_strongswan is not set
        CONFIG_PACKAGE_trojan=y
        # CONFIG_PACKAGE_vlmcsd is not set
        # CONFIG_PACKAGE_wireguard-tools is not set
        # CONFIG_PACKAGE_wol is not set
        # CONFIG_PACKAGE_zerotier is not set
        CONFIG_TARGET_KERNEL_PARTSIZE=64
        CONFIG_TARGET_ROOTFS_PARTSIZE=250
        CONFIG_boost-compile-visibility-hidden=y
        CONFIG_boost-runtime-shared=y
        CONFIG_boost-static-and-shared-libs=y
        CONFIG_boost-variant-release=y

  
        #
        # ========================固件定制部分结束========================
        #
        EOF
        sed -i 's/^[ \t]*//g' ./.config
        make defconfig
        # 网络配置信息，将从 zzz-default-settings 文件的第2行开始添加
        sed -i "2i # network config" ./package/lean/default-settings/files/zzz-default-settings
        # 默认 IP 地址，旁路由时不会和主路由的 192.168.1.1 冲突
        sed -i "3i uci set network.lan.ipaddr='192.168.50.6'" ./package/lean/default-settings/files/zzz-default-settings
        sed -i "4i uci set network.lan.proto='static'" ./package/lean/default-settings/files/zzz-default-settings # 静态 IP
        sed -i "5i uci set network.lan.type='bridge'" ./package/lean/default-settings/files/zzz-default-settings  # 接口类型：桥接
        sed -i "6i uci set network.lan.ifname='eth0'" ./package/lean/default-settings/files/zzz-default-settings  # 网络端口：默认 eth0，第一个接口
        sed -i "7i uci set network.lan.netmask='255.255.255.0'" ./package/lean/default-settings/files/zzz-default-settings    # 子网掩码
        sed -i "8i uci set network.lan.gateway='192.168.50.1'" ./package/lean/default-settings/files/zzz-default-settings  # 默认网关地址（主路由 IP）
        sed -i "9i uci set network.lan.dns='192.168.50.1'" ./package/lean/default-settings/files/zzz-default-settings  # 默认上游 DNS 地址
        sed -i "10i uci commit network\n" ./package/lean/default-settings/files/zzz-default-settings
    - name: Download package
      run: |
        cd lede && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build
      run: |
        cd lede
        make -j$(nproc)
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: lede/bin
